# -*- coding: utf-8 -*-
"""ScriptTCCIAssist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nleY-G9l9jNmKtF1teCDIE0pAXZw4AH2

# Imports
"""

### ---------- Imports ----------
import csv
from decimal import Decimal
import pandas as pd
import matplotlib.pyplot as plt

"""# Change .dat to .csv file

"""

### ---------- Generate .csv file ----------
with open("tcp-validation-first-tcp-rtt.dat") as infile, open("tcp-validation-first-tcp-rtt.csv", "w") as outfile:
    csv_writer = csv.writer(outfile)
    prev = ''
    csv_writer.writerow(['SIMULATION_TIME', 'RTT_TIME'])
    for line in infile.read().splitlines():
        prev = line.split()
        SIMULATION_TIME = prev[0].replace(',', '.')
        RTT_TIME = prev[1].replace(',', '.')
        csv_writer.writerow([SIMULATION_TIME, RTT_TIME])

"""# Read CSV file"""

### ---------- Read database ----------
dataset = pd.read_csv('tcp-validation-first-tcp-rtt.csv', sep=',')

dataset.head()

### ---------- verificando o tamanho do dataset ----------
print("Informações Sobre o Dataset")
print("Variáveis:\t {}".format(dataset.shape[1]))
print("Entradas:\t {}\n".format(dataset.shape[0]))
print("O dataset apresenta dados ausentes:\n")

### ---------- identificando os tipos das variáveis ----------
display(dataset.info())

### ----------- distribuição estátistica da base de dados -----------
dataset.describe()

"""# Graphs"""

plt.rcParams["figure.figsize"] = (20,25)
dataset.groupby(['SIMULATION_TIME', 'RTT_TIME']).size().groupby(level=0).apply(
     lambda x: 100 * x / x.sum()
 ).to_frame().unstack().plot(kind='bar',stacked=False,legend=False)
plt.title('Simulação x RTT')
plt.xlabel('RTT')
plt.legend(labels=['Tempo de Simulação', 'Tempo de RTT'])
plt.show()